#ifndef __SPEED_SEQUENCE_CONFIG_H__
#define __SPEED_SEQUENCE_CONFIG_H__

#include "speed_sequence.h"
#include "config.h"

#define CURRENT_GEAR_RATIO (19.0)
#define OLD_GEAR_RATIO (16.0)

/* We now have 6 modes, and only 4 gears */
#define NUM_MODES 6
#define NUM_GEARS 4

/****************************************************************************
 * Default Speeds for each gear
 ****************************************************************************/
#define RPM_TO_10RPM_CONVERSION_FACTOR (10U) /* Or S16 values */

#define GX_SAFE_AMPLITUDE (25 * RPM_TO_10RPM_CONVERSION_FACTOR) /* Example amplitude */


#define G0_DEFAULT_SPEED_RPM (315U) /* Measurements: with set up 600, 700, 800 900, gives:
                                        300, 360, 410, 470. */
#define G1_DEFAULT_SPEED_RPM (356U)
#define G2_DEFAULT_SPEED_RPM (395U)
#define G3_DEFAULT_SPEED_RPM (434U)

/*4200 = 280, 4600 = 318, 5000 = 345, 5500 = 380 (with 1:16)*/
  /* With 1:19, 6875 = 400,  */
  /* Equation for 1:16 ----> 13.39 x rpm + 401.76 = RPM_S16 */
#define G0_DEFAULT_SPEED_S16 (uint16_t) (G0_DEFAULT_SPEED_RPM * RPM_TO_10RPM_CONVERSION_FACTOR)
#define G1_DEFAULT_SPEED_S16 (uint16_t) (G1_DEFAULT_SPEED_RPM * RPM_TO_10RPM_CONVERSION_FACTOR)
#define G2_DEFAULT_SPEED_S16 (uint16_t) (G2_DEFAULT_SPEED_RPM * RPM_TO_10RPM_CONVERSION_FACTOR)
#define G3_DEFAULT_SPEED_S16 (uint16_t) (G3_DEFAULT_SPEED_RPM * RPM_TO_10RPM_CONVERSION_FACTOR)


/* With only 4 gears, we no longer define G4_DEFAULT_SPEED_S16, G5_DEFAULT_SPEED_S16 */
#define MIN_LEVEL_S16 (G0_DEFAULT_SPEED_S16 - 2 * GX_SAFE_AMPLITUDE)
#define SPEED_SEQUENCE_TRANSITION_TIME_MS (150U)

/* Infinite repeats for all modes (unchanged) */
#define M0_REPEAT UINT32_MAX
#define M1_REPEAT UINT32_MAX
#define M2_REPEAT UINT32_MAX
#define M3_REPEAT UINT32_MAX
#define M4_REPEAT UINT32_MAX
#define M5_REPEAT UINT32_MAX

/****************************************************************************
 * Mode 0 (Fixed Speed)
 *   Now has 3 steps
 ****************************************************************************/
#define M0_NUM_STEPS 3

/* We'll use the same SPEEDSEQ_TYPE_FIXED for all 3 steps */
#define M0_STEP1_TYPE SPEEDSEQ_TYPE_FIXED
#define M0_STEP2_TYPE SPEEDSEQ_TYPE_FIXED
#define M0_STEP3_TYPE SPEEDSEQ_TYPE_FIXED

/* Durations for new 3 steps in ms (10s, 15s, infinite) */
#define M0_STEP1_DURATION_MS 10000
#define M0_STEP2_DURATION_MS 15000
/* For the 3rd step, we'll just code in c-file as UINT32_MAX. 
   You could define a macro if you prefer, but not necessary. */

/* Levels for each of the 4 gears */
#define M0_G0_STEP1_LEVEL G0_DEFAULT_SPEED_S16 /* Client wanted to change speeds on mode 1. Now it just gets fixed speed mode. TODO: delete these time steps. */
#define M0_G0_STEP2_LEVEL G0_DEFAULT_SPEED_S16
#define M0_G0_STEP3_LEVEL G0_DEFAULT_SPEED_S16


#define M0_G1_LEVEL G1_DEFAULT_SPEED_S16
#define M0_G2_LEVEL G2_DEFAULT_SPEED_S16
#define M0_G3_LEVEL G3_DEFAULT_SPEED_S16

/****************************************************************************
 * Mode 1 (Sinusoidal)
 ****************************************************************************/
#define M1_NUM_STEPS 1
#define M1_STEP1_TYPE SPEEDSEQ_TYPE_SINE

/* Sinusoidal params per gear (4 gears) */
#define M1_G0_OFFSET    (G0_DEFAULT_SPEED_S16 - (G0_DEFAULT_SPEED_S16 / 5))
#define M1_G0_AMPLITUDE (G0_DEFAULT_SPEED_S16 / 5)
#define M1_G0_FREQUENCY 909

#define M1_G1_OFFSET    (G1_DEFAULT_SPEED_S16 - (G1_DEFAULT_SPEED_S16 / 5))
#define M1_G1_AMPLITUDE (G1_DEFAULT_SPEED_S16 / 5)
#define M1_G1_FREQUENCY 1020

#define M1_G2_OFFSET    (G2_DEFAULT_SPEED_S16 - (G2_DEFAULT_SPEED_S16 / 5))
#define M1_G2_AMPLITUDE (G2_DEFAULT_SPEED_S16 / 5)
#define M1_G2_FREQUENCY 1420

#define M1_G3_OFFSET    (G3_DEFAULT_SPEED_S16 - (G3_DEFAULT_SPEED_S16 / 5))
#define M1_G3_AMPLITUDE (G3_DEFAULT_SPEED_S16 / 5)
#define M1_G3_FREQUENCY 2000

/****************************************************************************
 * Mode 2
 *  Step1: Quadratic up
 *  Step2: Maintain upper
 *  Step3: Maintain near zero
 ****************************************************************************/
#define M2_NUM_STEPS 3
#define M2_STEP1_TYPE SPEEDSEQ_TYPE_QUADRATIC
#define M2_STEP2_TYPE SPEEDSEQ_TYPE_FIXED
#define M2_STEP3_TYPE SPEEDSEQ_TYPE_FIXED

/* Gear 0 */
#define M2_G0_STEP1_DURATION_MS 550
#define M2_G0_STEP2_DURATION_MS 800
#define M2_G0_STEP3_DURATION_MS 300
#define M2_G0_START_LEVEL (G0_DEFAULT_SPEED_S16 - GX_SAFE_AMPLITUDE)
#define M2_G0_END_LEVEL   G0_DEFAULT_SPEED_S16
#define M2_G0_ISINCREASING true

/* Gear 1 */
#define M2_G1_STEP1_DURATION_MS 500
#define M2_G1_STEP2_DURATION_MS 700
#define M2_G1_STEP3_DURATION_MS 250
#define M2_G1_START_LEVEL (G1_DEFAULT_SPEED_S16 - GX_SAFE_AMPLITUDE)
#define M2_G1_END_LEVEL   G1_DEFAULT_SPEED_S16
#define M2_G1_ISINCREASING true

/* Gear 2 */
#define M2_G2_STEP1_DURATION_MS 450
#define M2_G2_STEP2_DURATION_MS 600
#define M2_G2_STEP3_DURATION_MS 200
#define M2_G2_START_LEVEL (G2_DEFAULT_SPEED_S16 - GX_SAFE_AMPLITUDE)
#define M2_G2_END_LEVEL   G2_DEFAULT_SPEED_S16
#define M2_G2_ISINCREASING true

/* Gear 3 */
#define M2_G3_STEP1_DURATION_MS 400
#define M2_G3_STEP2_DURATION_MS 500
#define M2_G3_STEP3_DURATION_MS 150
#define M2_G3_START_LEVEL (G3_DEFAULT_SPEED_S16 - GX_SAFE_AMPLITUDE)
#define M2_G3_END_LEVEL   G3_DEFAULT_SPEED_S16
#define M2_G3_ISINCREASING true

/****************************************************************************
 * Mode 3
 *  Step1: Fixed
 *  Step2: near zero
 ****************************************************************************/
#define M3_NUM_STEPS 2
#define M3_STEP1_TYPE SPEEDSEQ_TYPE_FIXED
#define M3_STEP2_TYPE SPEEDSEQ_TYPE_FIXED

/* Gear 0 */
#define M3_G0_STEP1_DURATION_MS 120
#define M3_G0_STEP2_DURATION_MS 30
#define M3_G0_STEP1_LEVEL G0_DEFAULT_SPEED_S16
#define M3_G0_STEP2_LEVEL MIN_LEVEL_S16

/* Gear 1 */
#define M3_G1_STEP1_DURATION_MS 100
#define M3_G1_STEP2_DURATION_MS 23
#define M3_G1_STEP1_LEVEL G1_DEFAULT_SPEED_S16
#define M3_G1_STEP2_LEVEL MIN_LEVEL_S16

/* Gear 2 */
#define M3_G2_STEP1_DURATION_MS 80
#define M3_G2_STEP2_DURATION_MS 17
#define M3_G2_STEP1_LEVEL G2_DEFAULT_SPEED_S16
#define M3_G2_STEP2_LEVEL MIN_LEVEL_S16

/* Gear 3 */
#define M3_G3_STEP1_DURATION_MS 60
#define M3_G3_STEP2_DURATION_MS 10
#define M3_G3_STEP1_LEVEL G3_DEFAULT_SPEED_S16
#define M3_G3_STEP2_LEVEL MIN_LEVEL_S16

/****************************************************************************
 * Mode 4
 *  8 steps, alternating fixed/min
 ****************************************************************************/
#define M4_NUM_STEPS 8
#define M4_STEP1_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP2_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP3_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP4_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP5_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP6_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP7_TYPE SPEEDSEQ_TYPE_FIXED
#define M4_STEP8_TYPE SPEEDSEQ_TYPE_FIXED

/* Gear 0 */
#define M4_G0_SHORT_DURATION_MS 32
#define M4_G0_MEDIUM_DURATION_MS 39
#define M4_G0_LONG_DURATION_MS 120

#define M4_G0_STEP1_DURATION_MS M4_G0_MEDIUM_DURATION_MS
#define M4_G0_STEP2_DURATION_MS M4_G0_SHORT_DURATION_MS
#define M4_G0_STEP3_DURATION_MS M4_G0_MEDIUM_DURATION_MS
#define M4_G0_STEP4_DURATION_MS M4_G0_SHORT_DURATION_MS
#define M4_G0_STEP5_DURATION_MS M4_G0_MEDIUM_DURATION_MS
#define M4_G0_STEP6_DURATION_MS M4_G0_SHORT_DURATION_MS
#define M4_G0_STEP7_DURATION_MS M4_G0_LONG_DURATION_MS
#define M4_G0_STEP8_DURATION_MS M4_G0_SHORT_DURATION_MS

#define M4_G0_STEP1_LEVEL G0_DEFAULT_SPEED_S16
#define M4_G0_STEP2_LEVEL MIN_LEVEL_S16
#define M4_G0_STEP3_LEVEL G0_DEFAULT_SPEED_S16
#define M4_G0_STEP4_LEVEL MIN_LEVEL_S16
#define M4_G0_STEP5_LEVEL G0_DEFAULT_SPEED_S16
#define M4_G0_STEP6_LEVEL MIN_LEVEL_S16
#define M4_G0_STEP7_LEVEL G0_DEFAULT_SPEED_S16
#define M4_G0_STEP8_LEVEL MIN_LEVEL_S16

/* Gear 1 */
#define M4_G1_SHORT_DURATION_MS 23
#define M4_G1_MEDIUM_DURATION_MS 27
#define M4_G1_LONG_DURATION_MS 100

#define M4_G1_STEP1_DURATION_MS M4_G1_MEDIUM_DURATION_MS
#define M4_G1_STEP2_DURATION_MS M4_G1_SHORT_DURATION_MS
#define M4_G1_STEP3_DURATION_MS M4_G1_MEDIUM_DURATION_MS
#define M4_G1_STEP4_DURATION_MS M4_G1_SHORT_DURATION_MS
#define M4_G1_STEP5_DURATION_MS M4_G1_MEDIUM_DURATION_MS
#define M4_G1_STEP6_DURATION_MS M4_G1_SHORT_DURATION_MS
#define M4_G1_STEP7_DURATION_MS M4_G1_LONG_DURATION_MS
#define M4_G1_STEP8_DURATION_MS M4_G1_SHORT_DURATION_MS

#define M4_G1_STEP1_LEVEL G1_DEFAULT_SPEED_S16
#define M4_G1_STEP2_LEVEL MIN_LEVEL_S16
#define M4_G1_STEP3_LEVEL G1_DEFAULT_SPEED_S16
#define M4_G1_STEP4_LEVEL MIN_LEVEL_S16
#define M4_G1_STEP5_LEVEL G1_DEFAULT_SPEED_S16
#define M4_G1_STEP6_LEVEL MIN_LEVEL_S16
#define M4_G1_STEP7_LEVEL G1_DEFAULT_SPEED_S16
#define M4_G1_STEP8_LEVEL MIN_LEVEL_S16

/* Gear 2 */
#define M4_G2_SHORT_DURATION_MS 15
#define M4_G2_MEDIUM_DURATION_MS 18
#define M4_G2_LONG_DURATION_MS 80

#define M4_G2_STEP1_DURATION_MS M4_G2_MEDIUM_DURATION_MS
#define M4_G2_STEP2_DURATION_MS M4_G2_SHORT_DURATION_MS
#define M4_G2_STEP3_DURATION_MS M4_G2_MEDIUM_DURATION_MS
#define M4_G2_STEP4_DURATION_MS M4_G2_SHORT_DURATION_MS
#define M4_G2_STEP5_DURATION_MS M4_G2_MEDIUM_DURATION_MS
#define M4_G2_STEP6_DURATION_MS M4_G2_SHORT_DURATION_MS
#define M4_G2_STEP7_DURATION_MS M4_G2_LONG_DURATION_MS
#define M4_G2_STEP8_DURATION_MS M4_G2_SHORT_DURATION_MS

#define M4_G2_STEP1_LEVEL G2_DEFAULT_SPEED_S16
#define M4_G2_STEP2_LEVEL MIN_LEVEL_S16
#define M4_G2_STEP3_LEVEL G2_DEFAULT_SPEED_S16
#define M4_G2_STEP4_LEVEL MIN_LEVEL_S16
#define M4_G2_STEP5_LEVEL G2_DEFAULT_SPEED_S16
#define M4_G2_STEP6_LEVEL MIN_LEVEL_S16
#define M4_G2_STEP7_LEVEL G2_DEFAULT_SPEED_S16
#define M4_G2_STEP8_LEVEL MIN_LEVEL_S16

/* Gear 3 */
#define M4_G3_SHORT_DURATION_MS 10
#define M4_G3_MEDIUM_DURATION_MS 12
#define M4_G3_LONG_DURATION_MS 60

#define M4_G3_STEP1_DURATION_MS M4_G3_MEDIUM_DURATION_MS
#define M4_G3_STEP2_DURATION_MS M4_G3_SHORT_DURATION_MS
#define M4_G3_STEP3_DURATION_MS M4_G3_MEDIUM_DURATION_MS
#define M4_G3_STEP4_DURATION_MS M4_G3_SHORT_DURATION_MS
#define M4_G3_STEP5_DURATION_MS M4_G3_MEDIUM_DURATION_MS
#define M4_G3_STEP6_DURATION_MS M4_G3_SHORT_DURATION_MS
#define M4_G3_STEP7_DURATION_MS M4_G3_LONG_DURATION_MS
#define M4_G3_STEP8_DURATION_MS M4_G3_SHORT_DURATION_MS

#define M4_G3_STEP1_LEVEL G3_DEFAULT_SPEED_S16
#define M4_G3_STEP2_LEVEL MIN_LEVEL_S16
#define M4_G3_STEP3_LEVEL G3_DEFAULT_SPEED_S16
#define M4_G3_STEP4_LEVEL MIN_LEVEL_S16
#define M4_G3_STEP5_LEVEL G3_DEFAULT_SPEED_S16
#define M4_G3_STEP6_LEVEL MIN_LEVEL_S16
#define M4_G3_STEP7_LEVEL G3_DEFAULT_SPEED_S16
#define M4_G3_STEP8_LEVEL MIN_LEVEL_S16

/****************************************************************************
 * Mode 5
 *  5 steps with multiple sublevels
 ****************************************************************************/
#define M5_SAFE_AMPLITUDE (2000)
#define M5_EXTRA_SPEED_OFFSET (-300)

#define M5_NUM_STEPS 5
#define M5_STEP1_TYPE SPEEDSEQ_TYPE_FIXED
#define M5_STEP2_TYPE SPEEDSEQ_TYPE_FIXED
#define M5_STEP3_TYPE SPEEDSEQ_TYPE_FIXED
#define M5_STEP4_TYPE SPEEDSEQ_TYPE_FIXED
#define M5_STEP5_TYPE SPEEDSEQ_TYPE_FIXED

/* Gear 0 */
#define M5_G0_STEP1_DURATION_MS 4000
#define M5_G0_STEP2_DURATION_MS 4000
#define M5_G0_STEP3_DURATION_MS 4000
#define M5_G0_STEP4_DURATION_MS 6000
#define M5_G0_STEP5_DURATION_MS 12000

#define M5_G0_LEVEL1 (G0_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.75f * M5_SAFE_AMPLITUDE))
#define M5_G0_LEVEL2 (G0_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.50f * M5_SAFE_AMPLITUDE))
#define M5_G0_LEVEL3 (G0_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.25f * M5_SAFE_AMPLITUDE))
#define M5_G0_LEVEL4 (G0_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET)
#define M5_G0_LEVEL0 (G0_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.75f * M5_SAFE_AMPLITUDE))

/* Gear 1 */
#define M5_G1_STEP1_DURATION_MS 3000
#define M5_G1_STEP2_DURATION_MS 3000
#define M5_G1_STEP3_DURATION_MS 3000
#define M5_G1_STEP4_DURATION_MS 5000
#define M5_G1_STEP5_DURATION_MS 10000

#define M5_G1_LEVEL1 (G1_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.75f * M5_SAFE_AMPLITUDE))
#define M5_G1_LEVEL2 (G1_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.50f * M5_SAFE_AMPLITUDE))
#define M5_G1_LEVEL3 (G1_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.25f * M5_SAFE_AMPLITUDE))
#define M5_G1_LEVEL4 (G1_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET)
#define M5_G1_LEVEL0 (G0_DEFAULT_SPEED_S16)

/* Gear 2 */
#define M5_G2_STEP1_DURATION_MS 2000
#define M5_G2_STEP2_DURATION_MS 2000
#define M5_G2_STEP3_DURATION_MS 2000
#define M5_G2_STEP4_DURATION_MS 4000
#define M5_G2_STEP5_DURATION_MS 8000

#define M5_G2_LEVEL1 (G2_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.75f * M5_SAFE_AMPLITUDE))
#define M5_G2_LEVEL2 (G2_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.50f * M5_SAFE_AMPLITUDE))
#define M5_G2_LEVEL3 (G2_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.25f * M5_SAFE_AMPLITUDE))
#define M5_G2_LEVEL4 (G2_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET)
#define M5_G2_LEVEL0 (G0_DEFAULT_SPEED_S16)

/* Gear 3 */
#define M5_G3_STEP1_DURATION_MS 1000
#define M5_G3_STEP2_DURATION_MS 1000
#define M5_G3_STEP3_DURATION_MS 1000
#define M5_G3_STEP4_DURATION_MS 3000
#define M5_G3_STEP5_DURATION_MS 6000

#define M5_G3_LEVEL1 (G3_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.75f * M5_SAFE_AMPLITUDE))
#define M5_G3_LEVEL2 (G3_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.50f * M5_SAFE_AMPLITUDE))
#define M5_G3_LEVEL3 (G3_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET - (int16_t)(0.25f * M5_SAFE_AMPLITUDE))
#define M5_G3_LEVEL4 (G3_DEFAULT_SPEED_S16 + M5_EXTRA_SPEED_OFFSET)
#define M5_G3_LEVEL0 (G0_DEFAULT_SPEED_S16)

#endif // __SPEED_SEQUENCE_CONFIG_H__
